### ISSUE TITLE
Divide by zero

### ISSUE THREAD

**Issue by dragnmastr85** [nemosminer/NemosMiner-v2.5.1#313]
See screenshot below. I am getting a divide by zero error coming from the ps script. How can I fix this?

![image](https://user-images.githubusercontent.com/16077151/36515312-a21bd048-1746-11e8-8574-3a03a5c98bf5.png)

**Comment by mynameisrich** [comment]
I'm probably not the person to help, but which pools you are trying to load and is failing on might be useful to those who can help.  Perhaps paste your .bat file. It looks like zpool and ahashpool are loading OK, but the third pool isn't.

**Comment by valth0nis** [comment]
I'm having the same issue with ahashpool and both the regular bat file and the plue bat file.

**Comment by mynameisrich** [comment]
Even if you just have one pool listed in the bat file? It might be worth pasting what your bat file looks like

**Comment by valth0nis** [comment]
This is what's in mine. 

`powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\NPlusMiner-v1.3.ps1 -SelGPUDSTM '0 1 2 3 4 5 6 7' -SelGPUCC '0,1,2,3,4,5,6,7' -Currency USD -Passwordcurrency BTC -Wallet 1HgEov9W4Jwh8MQq9sLGkcrsHweyZrGAEn -Location US -ActiveMinerGainPct 3 -PoolName ahashpool -WorkerName ID=NPlusMiner13 -Type nvidia -Algorithm xevan,hsr,phi,tribus,c11,lbry,skein,groestl,sib,bitcore,x17,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,blake2s,skunk
`

**Comment by mynameisrich** [comment]
I just tried running the same command with less gpu's and didn't have any errors. Possible A/V is stopping it perhaps? I already have the benchmarks done though.

**Comment by dragnmastr85** [comment]
This is what mine looks like:
`powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\NPlusMiner-v1.3.ps1 -SelGPUDSTM '0 2' -SelGPUCC '0,2' -Currency USD -Passwordcurrency BTC -interval 60 -Wallet 17zxPhAtp4jwSE2NnA6NhAzkTjWA8o6H5J -Location US -ActiveMinerGainPct 3 -PoolName ahashpool,ahashpool24hr,hashrefinery,miningpoolhub,zpool,zpool24hr -Username dragnmastr85 -Workername gaming_rig -Type nvidia -Algorithm equihash,phi,hsr,xevan,tribus,c11,lbry,skein,groestl,sib,bitcore,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,skunk,keccak,x11evo,hmq1725,x17,lyra2z,timetravel,polytimos,decred,yescrypt,neoscrypt -Donate 0`

**Comment by yepla** [comment]
I have open the same issue yesterday nemo close it but i still have the issue with the last version :(

**Comment by valth0nis** [comment]
I've updated to the latest code and I'm still getting this error.

**Comment by ArchetypeZ28** [comment]
Same issue here.

**Comment by ging0044** [comment]
Do you guys have automatic payouts disabled? I know that on MPH you set it to 0 to disable it, but I am unsure of what the other pools do.

There is a part of the code there that divides your balance by your payout threshold, which would be 0 in this case, hence the error.

**Comment by dragnmastr85** [comment]
The bug fix resolved the error message but doesnt address the undermining cause. I do not have automatic payouts disable in either hashrefinery or MPH.
![image](https://user-images.githubusercontent.com/16077151/36625464-032f9574-18ee-11e8-8505-6e7d4f6d6501.png)

**Comment by valth0nis** [comment]
I'm using ahashpool is that supported? Right now it's not displaying any earning data for me.

**Comment by valth0nis** [comment]
I saw this was posted on nplusminer repo as well. Disregarding this thread.

**Comment by nemosminer** [comment]
use latest release:
https://github.com/nemosminer/NemosMiner-v2.5/releases/download/v2.5/NemosMiner-v2.5.zip
all is well tested ahashpool with 1x1070 6x1070ti & 6x1080ti

**Comment by valth0nis** [comment]
@nemosminer testing now. i'll report back thanks.

**Comment by nemosminer** [comment]
@dragnmastr85 "-PoolName ahashpool,ahashpool24hr,hashrefinery,miningpoolhub,zpool,zpool24hr"

i only test with single pool bat files i cant guarantee anything when your trying to run 6 different pools at once...

**Comment by valth0nis** [comment]
@nemosminer do i need to enter in anymore information besides the number of GPU's and the wallet address to get this working? Is there any other file I need to modify? Maybe the earning tracker bat file? Or enable the paremeters in the earningtrackerjob ps file? As of right now I'm still not getting any earnings for ahashpool.
![image](https://user-images.githubusercontent.com/36717972/36634412-eca2f324-1969-11e8-8468-ba49bd002ef1.png)

**Comment by nemosminer** [comment]
instructions:

edit startpoolname.bat

1.change BTC address to yours

2.select how many gpu's you have eg: (1gpu dstm 0 cc 0) (2gpu dstm 0 1 cc 0,1) (6gpu dstm 0 1 2 3 4 5 cc 0,1,2,3,4,5)

3.remove any algos you do not want to mine

4.there is a 5minute per day fee (0.3%), that can be changed by modifying -Donate 5 to 0.

5.save & run startpoolname.bat

**Comment by nemosminer** [comment]
have you just started mining with ahashpool with a new btc address it may take awhile for you balance to start showing while your balance is 0 it will display "Automatic Payouts disabled"

**Comment by nemosminer** [comment]
@valth0nis 

it working correctly just let it run wait for "Trust Level" to go up it start displaying your info soon it needs time to work...

**Comment by valth0nis** [comment]
Ok I'll give it some time. And no I've been mining on ahashpool for about 3 months now with the same address. I'll let you know what I'm getting after a few hours.

**Comment by nemosminer** [comment]
single 1070 gaming pc: https://imgur.com/a/SZ6eW

**Comment by nemosminer** [comment]
single 1070 gaming pc: https://imgur.com/a/l4oXX  note:zpool test

**Comment by valth0nis** [comment]
@nemosminer The trust level is at 100% and still no change.
![image](https://user-images.githubusercontent.com/36717972/36637339-ca16c6f6-199f-11e8-8a19-56f1f42b33c9.png)

**Comment by nemosminer** [comment]
ok thankyou

**Comment by nemosminer** [comment]
try v2.5.1 :  https://github.com/nemosminer/NemosMiner-v2.5.1/archive/master.zip

im testing it atm myself on 3 different test rigs single 1070gaming pc / 6x1070ti's / 6x1080tis 

so far all is going well

**Comment by nemosminer** [comment]
fixed :  )

**Comment by nemosminer** [comment]
@valth0nis  try a different btc address from a different type of wallet...

**Comment by valth0nis** [comment]
Will do. I'll get back to you.

**Comment by valth0nis** [comment]
@nemosminer is there a specific wallet you recommend? Which one do you use?

**Comment by nemosminer** [comment]
https://bitcoin.org/en/choose-your-wallet

"Electrum"

**Comment by valth0nis** [comment]
That's the one I'm using now lol.

**Comment by nemosminer** [comment]
.... i don't know why it won't work... if you run with default btc address which is mine does it show you btc balance and all stats? its only stats at the end of the day  not effecting hashing or profits..... you wont get the error  message anymore just a normal message "can't retrieve info"

**Comment by valth0nis** [comment]
I get the same error with your BTC address.
![image](https://user-images.githubusercontent.com/36717972/36648372-579b7090-1a58-11e8-95a2-c61521b4f9ab.png)

**Comment by valth0nis** [comment]
@nemosminer where is the payment threshold parameter being set?
