### ISSUE TITLE
Average BTC/D not lining up with stats

### ISSUE THREAD

**Issue by mynameisrich** [nemosminer/NemosMiner-v2.5.1#322]
I have a 4 x 1070 rig going for 3-4 days on ahashpool using ahashpoolplus with a gaming PC also going on the same btc address concurrently. 

I understand it takes a few days to get the mature blocks plus autoconversions through the system etc so didn't bother posting til now, but it seems the average btc/d numbers are a fair bit out from what it's showing in the table below it (about 20-30% from my calcs). Even though the numbers in the below table do fluctuate, I haven't seen them below 0.95 mBTC at any point

Screenshot taken from the 4 x 1070 rig.. the PC also has a 1070 so the numbers should be around 15-20% higher than the numbers shown down the bottom.

Running v2.5

![image](https://user-images.githubusercontent.com/36323156/36637341-4ace0b5e-1a2e-11e8-8e79-470f6877fa42.png)

**Comment by nemosminer** [comment]
try latest release was only released 24hour ago....

https://github.com/nemosminer/NemosMiner-v2.5/releases/download/v2.5/NemosMiner-v2.5.zip
