### ISSUE TITLE
After restarting the miner all stats on benchmarks are lost

### ISSUE THREAD

**Issue by tr1l3r** [nemosminer/NemosMiner-v2.5.1#323]
Hi Nemo. I don't know if it's a bug or it's the way miner is supposed to work, but after all benchmarks are done, all of them dissappear and only the one gpus are working on is shown. Also donations are acting weird. I'm trying to donate to you the the software keeps donating to another random btc wallet.

**Comment by valth0nis** [comment]
If you press the 's' key it will show you the full stats after the next refresh.

**Comment by nemosminer** [comment]
no bug
