### ISSUE TITLE
v2.5.1 = master

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner-v2.5.1#324]
Updated Ccminerskunk (faster hashing)
Update UI (during benchmarks)
Update zpool algos list (removed timetravel,keccak)

**Comment by valth0nis** [comment]
I hate to post this but I just updated to 2.5.1 and I'm getting the divide by zero error again. 
![image](https://user-images.githubusercontent.com/36717972/36646233-9b64ff08-1a3a-11e8-9fc0-7cb95fdd347e.png)

**Comment by nemosminer** [comment]
thanks
