### ISSUE TITLE
compile and test ccminer spmod-phi

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner-v2.5.1#330]
compile 32bit and 64bit version and test against current ccminer alexis78-phi 

test with (1070 and 1080ti)

https://github.com/nemosminer/ccminer-anorganix--spmod
https://github.com/nemosminer/ccminer-anorganix--spmod/blob/master/README.txt

**Comment by jrafaelmdo** [comment]
@nemosminer 

Are you going to upload the compiled version ?

Thanks

**Comment by nemosminer** [comment]
@jrafaelmdo once i have it compiled and tested i will add a release to :  https://github.com/nemosminer/ccminer-anorganix--spmod/releases

i'll make it todays job...
