### ISSUE TITLE
Tribus Errors

### ISSUE THREAD

**Issue by Minimag47** [nemosminer/NemosMiner-v2.5.1#332]
After the 2.5.1 update I am receiving nothing but cpu can't validate errors when trying to hash Tribus. 2.5 worked just fine.

**Comment by nemosminer** [comment]
https://imgur.com/a/Ta8ac

**Comment by Minimag47** [comment]
Mine will work for the first 5 minute benchmark, then get about 4 minutes
into the second one and then just get continual errors. I've rerun it a
dozen times and it never successfully gets through the second benchmark.
All other algos go through fine. As stated in 2.5 I had no issues at all.
Is the tribus miner the same that was in 2.5? Just trying to see if I can
help.

**Comment by nemosminer** [comment]
its excatly the same now changes tribus is fine...

**Comment by Minimag47** [comment]
Damn, ok. I'll trouble shoot my end and run the 2.5 version and see if I
still get the same errors.

**Comment by nemosminer** [comment]
https://imgur.com/a/n1end
