### ISSUE TITLE
You do not have sufficient access rights

### ISSUE THREAD

**Issue by valth0nis** [nemosminer/NemosMiner-v2.5.1#333]
I'm getting this new error on one of my rigs. The other 3 or running just fine and they all have the same set up. I've made sure to add the nwemosminer folder to the exclusion list in windows defender and i've downloaded the vcruntime140 files but nothing is working. The rig is mining it just keeps trying to download ccmineralexis78cuda and ccminertpruvot over and over again and failing.
![2018-02-27_16-05-27](https://user-images.githubusercontent.com/36717972/36757868-3e60f754-1bd8-11e8-86f0-506d6dde8775.png)

**Comment by jimmykl** [comment]
Did you manually add vcruntime140 to the miner folder? I've never had to do anything manually with the miners. What happens if you delete the entire Bin folder and run it again?

**Comment by valth0nis** [comment]
Deleting the bin folder fixed the issue. Thanks!
