### ISSUE TITLE
Mining software

### ISSUE THREAD

**Issue by Dekablade01** [nemosminer/NemosMiner-v2.5.1#336]
From my understanding `CCMiner.tpruvot` support
`X17`, `lyra2v2`, `equihash`, `blake2s` why just use it for `bitcore` ? Because I think it's the most famous.

and why
`Polytimos` for `X17`, `Blake2s`, `lyra2v2`, ...
and the other algos.

**Comment by jrafaelmdo** [comment]
@Dekablade01 

ccminer is not the fastest for x17, lyra2v2, or blake2s  compared to Polytimos or Alexis78HSR.

Its almost as fast as alexis78PHI in PHI algo but extremely bad at equihash when compared to Excavator or ewbf.

You are free to edit the miner files and add the algos yourself and let the benchmark run, once complete the software will pick the fastest miner for each algo.
