### ISSUE TITLE
CCMiner is not working

### ISSUE THREAD

**Issue by Dekablade01** [nemosminer/NemosMiner-v2.5.1#339]
I configured virtual memory to 64GB - 70GB,
 cuda 9,
 39x.xx version ( the latest one ), 
no customized overclocking 1080Ti ( 7 GPUs ) 

after run few minutes `CCMiner is not working`

**Comment by nemosminer** [comment]
which algo i have my own 6x1080ti rig running latest v2.5.1 atm

can you send me a screen shot of ccminer crashing?

**Comment by Dekablade01** [comment]
Ok when it's reproduce again I'll take the ss

**Comment by nemosminer** [comment]
ok well my rigs are allgood i'll reopen this if you can show me what problem you are having
